# Expensify CodeDeploy AppSpec.yml
version: 0.0
os: linux
files:
- source: /
   destination: /home/ec2-user/expensify
hooks:
  AfterInstall:
    - location: server/depend.sh
      timeout: 1200
      runas: ec2-user
  ApplicationStart:
    - location: server/start_server.sh
      timeout: 300
      runas: ec2-user
